---
services:
  oravo:
    image: ghcr.io/oravo/oravo:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://oravo:oravo@db:5432/oravo
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
      DISABLE_REGISTRATION: false
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: oravo
      POSTGRES_USER: oravo
      POSTGRES_PASSWORD: oravo
    volumes:
      - oravo-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  oravo-db-data:
